run:
  timeout: 5m
  tests: true
  skip-dirs:
    - internal/gen
    - .local
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_grpc\\.pb\\.go$"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - ineffassign
    - bodyclose
    - prealloc
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocognit
    - gocyclo
  disable:
    - lll
    - funlen
    - gochecknoglobals
    - gochecknoinits

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
      - name: comment-spacings
        severity: warning
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - gocognit
    - path: internal/gen
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0

